module.exports = {
  "eslint-comments/require-description": "off",
  "import/no-default-export": "off",
  "import/no-extraneous-dependencies": "off",
  "import/order": "off",
  "jsx-a11y/heading-has-content": "off",
  "no-implicit-coercion": "off",
  "no-unused-vars": "off", // enforced by tsconfig -> "noUnusedLocals": true
  "react/function-component-definition": "off",
  "react/jsx-sort-props": "off",
  "react/no-unknown-property": "off",
  "react/no-unstable-nested-components": "off",
  "unicorn/filename-case": "off",
  "@next/next/no-html-link-for-pages": "off",
  "@typescript-eslint/array-type": "off",
  "@typescript-eslint/consistent-type-definitions": "off",
  "@typescript-eslint/consistent-type-imports": "off",
  "@typescript-eslint/explicit-function-return-type": "off",
  "@typescript-eslint/naming-convention": "off",
  "@typescript-eslint/no-empty-interface": "off",
  "@typescript-eslint/no-shadow": "off",
  "@typescript-eslint/no-unnecessary-condition": "off",
  "@typescript-eslint/no-unsafe-argument": "off",
  "@typescript-eslint/no-unsafe-assignment": "off",
  "@typescript-eslint/no-unsafe-member-access": "off",
  "@typescript-eslint/no-unused-vars": "off",
};
