export function getTimezoneOptions() {
    return [
        // UTC
        { value: "UTC", label: "UTC" },

        // North America
        { value: "America/New_York", label: "Eastern Time (ET)" },
        { value: "America/Chicago", label: "Central Time (CT)" },
        { value: "America/Denver", label: "Mountain Time (MT)" },
        { value: "America/Los_Angeles", label: "Pacific Time (PT)" },
        { value: "America/Anchorage", label: "Alaska Time (AKT)" },
        { value: "Pacific/Honolulu", label: "Hawaii Time (HST)" },
        { value: "America/Toronto", label: "Eastern Time - Toronto" },
        { value: "America/Vancouver", label: "Pacific Time - Vancouver" },
        { value: "America/Mexico_City", label: "Central Time - Mexico City" },

        // Europe
        { value: "Europe/London", label: "Greenwich Mean Time (GMT)" },
        { value: "Europe/Paris", label: "Central European Time (CET)" },
        { value: "Europe/Berlin", label: "Central European Time - Berlin" },
        { value: "Europe/Rome", label: "Central European Time - Rome" },
        { value: "Europe/Madrid", label: "Central European Time - Madrid" },
        { value: "Europe/Amsterdam", label: "Central European Time - Amsterdam" },
        { value: "Europe/Brussels", label: "Central European Time - Brussels" },
        { value: "Europe/Vienna", label: "Central European Time - Vienna" },
        { value: "Europe/Zurich", label: "Central European Time - Zurich" },
        { value: "Europe/Stockholm", label: "Central European Time - Stockholm" },
        { value: "Europe/Oslo", label: "Central European Time - Oslo" },
        { value: "Europe/Copenhagen", label: "Central European Time - Copenhagen" },
        { value: "Europe/Helsinki", label: "Eastern European Time (EET)" },
        { value: "Europe/Athens", label: "Eastern European Time - Athens" },
        { value: "Europe/Bucharest", label: "Eastern European Time - Bucharest" },
        { value: "Europe/Sofia", label: "Eastern European Time - Sofia" },
        { value: "Europe/Warsaw", label: "Central European Time - Warsaw" },
        { value: "Europe/Prague", label: "Central European Time - Prague" },
        { value: "Europe/Budapest", label: "Central European Time - Budapest" },
        { value: "Europe/Dublin", label: "Greenwich Mean Time - Dublin" },
        { value: "Europe/Lisbon", label: "Western European Time (WET)" },
        { value: "Europe/Moscow", label: "Moscow Time (MSK)" },
        { value: "Europe/Kiev", label: "Eastern European Time - Kyiv" },
        { value: "Europe/Istanbul", label: "Turkey Time (TRT)" },

        // Asia
        { value: "Asia/Tokyo", label: "Japan Standard Time (JST)" },
        { value: "Asia/Shanghai", label: "China Standard Time (CST)" },
        { value: "Asia/Seoul", label: "Korea Standard Time (KST)" },
        { value: "Asia/Singapore", label: "Singapore Time (SGT)" },
        { value: "Asia/Bangkok", label: "Indochina Time (ICT)" },
        { value: "Asia/Manila", label: "Philippine Time (PHT)" },
        { value: "Asia/Jakarta", label: "Western Indonesian Time (WIB)" },
        { value: "Asia/Kuala_Lumpur", label: "Malaysia Time (MYT)" },
        { value: "Asia/Hong_Kong", label: "Hong Kong Time (HKT)" },
        { value: "Asia/Taipei", label: "Taipei Time (TST)" },
        { value: "Asia/Calcutta", label: "India Standard Time (IST)" },
        { value: "Asia/Karachi", label: "Pakistan Standard Time (PKT)" },
        { value: "Asia/Dhaka", label: "Bangladesh Standard Time (BST)" },
        { value: "Asia/Kabul", label: "Afghanistan Time (AFT)" },
        { value: "Asia/Tehran", label: "Iran Standard Time (IRST)" },
        { value: "Asia/Dubai", label: "Gulf Standard Time (GST)" },
        { value: "Asia/Riyadh", label: "Arabia Standard Time (AST)" },
        { value: "Asia/Jerusalem", label: "Israel Standard Time (IST)" },
        { value: "Asia/Baghdad", label: "Arabia Standard Time - Baghdad" },
        { value: "Asia/Kuwait", label: "Arabia Standard Time - Kuwait" },
        { value: "Asia/Qatar", label: "Arabia Standard Time - Qatar" },
        { value: "Asia/Bahrain", label: "Arabia Standard Time - Bahrain" },
        { value: "Asia/Muscat", label: "Gulf Standard Time - Muscat" },
        { value: "Asia/Yerevan", label: "Armenia Time (AMT)" },
        { value: "Asia/Tbilisi", label: "Georgia Time (GET)" },
        { value: "Asia/Baku", label: "Azerbaijan Time (AZT)" },
        { value: "Asia/Tashkent", label: "Uzbekistan Time (UZT)" },
        { value: "Asia/Almaty", label: "Kazakhstan Time (ALMT)" },
        { value: "Asia/Novosibirsk", label: "Novosibirsk Time (NOVT)" },
        { value: "Asia/Krasnoyarsk", label: "Krasnoyarsk Time (KRAT)" },
        { value: "Asia/Irkutsk", label: "Irkutsk Time (IRKT)" },
        { value: "Asia/Yakutsk", label: "Yakutsk Time (YAKT)" },
        { value: "Asia/Vladivostok", label: "Vladivostok Time (VLAT)" },
        { value: "Asia/Magadan", label: "Magadan Time (MAGT)" },
        { value: "Asia/Kamchatka", label: "Kamchatka Time (PETT)" },
        { value: "Asia/Anadyr", label: "Anadyr Time (ANAT)" },

        // Australia & Oceania
        { value: "Australia/Sydney", label: "Australian Eastern Time (AET)" },
        { value: "Australia/Melbourne", label: "Australian Eastern Time - Melbourne" },
        { value: "Australia/Brisbane", label: "Australian Eastern Time - Brisbane" },
        { value: "Australia/Adelaide", label: "Australian Central Time (ACT)" },
        { value: "Australia/Perth", label: "Australian Western Time (AWT)" },
        { value: "Australia/Darwin", label: "Australian Central Time - Darwin" },
        { value: "Australia/Hobart", label: "Australian Eastern Time - Hobart" },
        { value: "Pacific/Auckland", label: "New Zealand Standard Time (NZST)" },
        { value: "Pacific/Fiji", label: "Fiji Time (FJT)" },
        { value: "Pacific/Guam", label: "Chamorro Standard Time (ChST)" },
        { value: "Pacific/Saipan", label: "Chamorro Standard Time - Saipan" },
        { value: "Pacific/Port_Moresby", label: "Papua New Guinea Time (PGT)" },
        { value: "Pacific/Noumea", label: "New Caledonia Time (NCT)" },
        { value: "Pacific/Tahiti", label: "Tahiti Time (TAHT)" },

        // South America
        { value: "America/Sao_Paulo", label: "Brasília Time (BRT)" },
        { value: "America/Buenos_Aires", label: "Argentina Time (ART)" },
        { value: "America/Santiago", label: "Chile Time (CLT)" },
        { value: "America/Lima", label: "Peru Time (PET)" },
        { value: "America/Bogota", label: "Colombia Time (COT)" },
        { value: "America/Caracas", label: "Venezuela Time (VET)" },
        { value: "America/La_Paz", label: "Bolivia Time (BOT)" },
        { value: "America/Asuncion", label: "Paraguay Time (PYT)" },
        { value: "America/Montevideo", label: "Uruguay Time (UYT)" },
        { value: "America/Cayenne", label: "French Guiana Time (GFT)" },

        // Africa
        { value: "Africa/Cairo", label: "Eastern European Time - Cairo" },
        { value: "Africa/Johannesburg", label: "South Africa Standard Time (SAST)" },
        { value: "Africa/Lagos", label: "West Africa Time (WAT)" },
        { value: "Africa/Nairobi", label: "East Africa Time (EAT)" },
        { value: "Africa/Casablanca", label: "Western European Time - Casablanca" },
        { value: "Africa/Algiers", label: "Central European Time - Algiers" },
        { value: "Africa/Tunis", label: "Central European Time - Tunis" },
        { value: "Africa/Tripoli", label: "Eastern European Time - Tripoli" },
        { value: "Africa/Khartoum", label: "Central Africa Time (CAT)" },
        { value: "Africa/Addis_Ababa", label: "East Africa Time - Addis Ababa" },
        { value: "Africa/Dar_es_Salaam", label: "East Africa Time - Dar es Salaam" },
        { value: "Africa/Harare", label: "Central Africa Time - Harare" },
        { value: "Africa/Luanda", label: "West Africa Time - Luanda" },
        { value: "Africa/Kinshasa", label: "West Africa Time - Kinshasa" },
        { value: "Africa/Lubumbashi", label: "Central Africa Time - Lubumbashi" },
        { value: "Africa/Lusaka", label: "Central Africa Time - Lusaka" },
        { value: "Africa/Maputo", label: "Central Africa Time - Maputo" },
        { value: "Africa/Windhoek", label: "Central Africa Time - Windhoek" },
        { value: "Africa/Gaborone", label: "Central Africa Time - Gaborone" },
        { value: "Africa/Maseru", label: "South Africa Standard Time - Maseru" },
        { value: "Africa/Mbabane", label: "South Africa Standard Time - Mbabane" },
        { value: "Africa/Libreville", label: "West Africa Time - Libreville" },
        { value: "Africa/Douala", label: "West Africa Time - Douala" },
        { value: "Africa/Brazzaville", label: "West Africa Time - Brazzaville" },
        { value: "Africa/Bangui", label: "West Africa Time - Bangui" },
        { value: "Africa/Ndjamena", label: "West Africa Time - Ndjamena" },
        { value: "Africa/Malabo", label: "West Africa Time - Malabo" },
        { value: "Africa/Sao_Tome", label: "Sao Tome Time (GMT)" },
        { value: "Africa/Accra", label: "Greenwich Mean Time - Accra" },
        { value: "Africa/Dakar", label: "Greenwich Mean Time - Dakar" },
        { value: "Africa/Bamako", label: "Greenwich Mean Time - Bamako" },
        { value: "Africa/Conakry", label: "Greenwich Mean Time - Conakry" },
        { value: "Africa/Freetown", label: "Greenwich Mean Time - Freetown" },
        { value: "Africa/Monrovia", label: "Greenwich Mean Time - Monrovia" },
        { value: "Africa/Banjul", label: "Greenwich Mean Time - Banjul" },
        { value: "Africa/Bissau", label: "Greenwich Mean Time - Bissau" },
        { value: "Africa/Nouakchott", label: "Greenwich Mean Time - Nouakchott" },
        { value: "Africa/Ouagadougou", label: "Greenwich Mean Time - Ouagadougou" },
        { value: "Africa/Porto-Novo", label: "West Africa Time - Porto-Novo" },
        { value: "Africa/Lome", label: "Greenwich Mean Time - Lome" },
        { value: "Africa/Niamey", label: "West Africa Time - Niamey" },
        { value: "Africa/El_Aaiun", label: "Western European Time - El Aaiun" },
        { value: "Africa/Ceuta", label: "Central European Time - Ceuta" },
        { value: "Africa/Asmera", label: "East Africa Time - Asmara" },
        { value: "Africa/Djibouti", label: "East Africa Time - Djibouti" },
        { value: "Africa/Mogadishu", label: "East Africa Time - Mogadishu" },
        { value: "Africa/Kampala", label: "East Africa Time - Kampala" },
        { value: "Africa/Kigali", label: "Central Africa Time - Kigali" },
        { value: "Africa/Bujumbura", label: "Central Africa Time - Bujumbura" },
        { value: "Africa/Blantyre", label: "Central Africa Time - Blantyre" },
        { value: "Africa/Juba", label: "East Africa Time - Juba" },
    ];
}